# Generated by Django 4.0.4 on 2022-04-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_str', models.CharField(blank=True, max_length=512, null=True)),
                ('a_bool', models.BooleanField(default=False)),
                ('a_int', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'TableA',
                'verbose_name_plural': 'Tables of A',
            },
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_str', models.CharField(blank=True, max_length=512, null=True)),
                ('b_bool', models.BooleanField(default=False)),
                ('b_int', models.IntegerField(default=0)),
                ('table_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_b_to_a', to='redis_app.tablea')),
            ],
            options={
                'verbose_name': 'TableB',
                'verbose_name_plural': 'Tables ot B',
            },
        ),
        migrations.CreateModel(
            name='TableC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_str', models.CharField(blank=True, max_length=512, null=True)),
                ('c_bool', models.BooleanField(default=False)),
                ('c_int', models.IntegerField(default=0)),
                ('table_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_c_to_b', to='redis_app.tableb')),
            ],
            options={
                'verbose_name': 'TableC',
                'verbose_name_plural': 'Table of C',
            },
        ),
        migrations.CreateModel(
            name='TableD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_str', models.CharField(blank=True, max_length=512, null=True)),
                ('d_bool', models.BooleanField(default=False)),
                ('d_int', models.IntegerField(default=0)),
                ('table_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_d_to_c', to='redis_app.tablec')),
            ],
            options={
                'verbose_name': 'TableD',
                'verbose_name_plural': 'Table of D',
            },
        ),
        migrations.CreateModel(
            name='TableE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_str', models.CharField(blank=True, max_length=512, null=True)),
                ('e_bool', models.BooleanField(default=False)),
                ('e_int', models.IntegerField(default=0)),
                ('table_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_e_to_d', to='redis_app.tabled')),
            ],
            options={
                'verbose_name': 'TableE',
                'verbose_name_plural': 'Table of E',
            },
        ),
    ]
